parameters:
  name: ''
  pool: ''
  sign: false

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - script: "echo first step"
  - ${{ if eq(parameters.sign, 'true') }}:
    - script: "echo conditional sign step"