trigger: none

pool:
  #  vmImage: 'ubuntu-latest'
  name: selfhosted

steps:

# Agent openjdk and maven on the build agent
# apt update && apt install -y openjdk-11-jdk && sudo install -y maven
# setup env in the maven task as  shown below

 - task: Maven@4
   inputs:
     mavenPomFile: 'pom.xml'
     mavenOptions: '-Xmx3072m'
     javaHomeOption: 'JDKVersion'
     jdkVersionOption: '1.11'
     jdkArchitectureOption: 'x64'
     publishJUnitResults: false
     testResultsFiles: '**/surefire-reports/TEST-*.xml'
     goals: 'package'
   env:
     JAVA_HOME_11_X64: "/usr/lib/jvm/java-11-openjdk-amd64"
     PATH: "/usr/lib/jvm/java-11-openjdk-amd64/bin:$(PATH)"     
