trigger:
  branches:
    exclude:
      - '*'  # Prevent regular push triggers
pr:
  branches:
    exclude:
      - '*'  # Don't trigger on PRs
strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'
  maxParallel: 3 # max 3 parallel jobs    

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- script: |
    npm -v