trigger:
  branches:
    exclude:
      - '*'  # Prevent regular push triggers
pr:
  branches:
    exclude:
      - '*'  # Don't trigger on PRs

resources:
  containers:
  - container: u22
    image: ubuntu:22.04
  - container: u24
    image: ubuntu:24.04


jobs:
- job: RunInContainer
  pool:
    # vmImage: 'ubuntu:latest'
    name: selfhosted

  strategy:
    matrix:
      ubuntu22:
        containerResource: u22
      ubuntu24:
        containerResource: u24

  container: $[ variables['containerResource'] ]

  steps:
  - script: printenv
