trigger:
  branches:
    exclude:
      - '*'  # Prevent regular push triggers
pr:
  branches:
    exclude:
      - '*'  # Don't trigger on PRs

pool: 
  vmImage: ubuntu-latest

jobs:
- job: PreWork
  steps:
  - script: |
      echo "do some prep work"

- job: PostWork
  dependsOn: PreWork
  pool: 
      vmImage: windows-latest
  steps:
  - script: |
      echo "Do post-work using a different hosted image"
