trigger:
  branches:
    exclude:
      - '*'  # Prevent regular push triggers

pr:
  branches:
    exclude:
      - '*'  # Don't trigger on PRs

pool: 
  vmImage: ubuntu-latest

jobs:
- job: PreWork
  steps:
  - script: "Do pre-work"

- job: PostWork
  pool: 
      vmImage: windows-latest
  steps:
  - script: "Do post-work using a different hosted image"
