trigger:
  branches:
    exclude:
      - '*'  # Prevent regular push triggers

pr:
  branches:
    exclude:
      - '*'  # Don't trigger on PRs

pool:
  # vmImage: ubuntu-latest
  name: selfhosted
  
jobs:
- job: simpleJob
  displayName: "Run simple job on self-hosted agent"

  steps:
  - script: |
      echo "Hello, this is a simple job running on a self-hosted agent named 'agent'!"
    displayName: "Run simple script"
